### ISSUE TITLE
Testing with Clojure 1.8.0-beta1

### ISSUE THREAD

**Issue by mrrodriguez** [ztellman/riddley#18]
Using potemkin/potemkin version "0.4.1", which uses riddley version "0.1.10" with Clojure version 1.8.0-beta1 I get failures.

This could be an issue for potemkin, but it looks to possibly be an issue with riddley instead.

```clj
(require 'potemkin)

(potemkin/defprotocol+ MyP (foo [this]))
UnsupportedOperationException   clojure.lang.APersistentVector.key (APersistentVector.java:452)
```

The rest of the stack:
```clj
(pst)
UnsupportedOperationException 
	clojure.lang.APersistentVector.key (APersistentVector.java:452)
	clojure.lang.APersistentVector.getKey (APersistentVector.java:131)
	clojure.core/key (core.clj:1516)
	clojure.core/key (core.clj:-1)
	riddley.walk/walk-exprs/fn--3648 (walk.clj:227)
	clojure.core/apply (core.clj:645)
	clojure.core/with-bindings* (core.clj:1874)
	clojure.core/with-bindings* (core.clj:-1)
	riddley.walk/walk-exprs (walk.clj:192)
	riddley.walk/walk-exprs (walk.clj:-1)
	clojure.core/partial/fn--4755 (core.clj:2522)
	clojure.core/map/fn--4777 (core.clj:2639)
;= nil
```

**Comment by martinraison** [comment]
I'm also having the same issue. The simplest repro I have so far is:

    (riddley.walk/macroexpand-all [])

This is working with 1.7.0, not with 1.8.0-beta1

**Comment by martinraison** [comment]
After looking a bit further, it seems this happens because in 1.8.0, `APersistentVector` implements `IMapEntry`.

**Comment by mrrodriguez** [comment]
I do wonder why Clojure implements this Map$Entry interface now on APersistentVector when they do not support the key or val functions? 

I appreciate you finding the issue and submitting a fix in riddley for this though.

**Comment by martinraison** [comment]
The key and val functions work, but only when the length of the vector is equal to 2, which seems like a bug-prone behavior. I wonder what are the reasons for this change.

**Comment by puredanger** [comment]
Just for my own edification, this is due to the ordering of these checks right? 

https://github.com/ztellman/riddley/blob/master/src/riddley/walk.clj#L225-L233

**Comment by mrrodriguez** [comment]
@puredanger  I'd think that if you flip the order of those two checks then all map entries would funnel into the the `(vector? x)` branch and never reach the `(instance? java.util.Map$Entry x)`.
So all map entries wouldn't be preserved as map entries in the walk, which I think is the intent of the function (just guessing at that, I haven't worked in this lib directly).

e.g.
```clj
(instance? java.util.Map$Entry (first {:a 1}))
;= true

(vector? (first {:a 1}))
;= true
```

Unless I'm not understanding something here.
