### ISSUE TITLE
Appears to only work on the top-level form

### ISSUE THREAD

**Issue by lincoln-b** [ztellman/riddley#26]
Can you help me understand why this:

    (riddley.walk/walk-exprs identity reverse '(defn xyz [x y z] (+ x (+ y z))))

returns this:

    (([x y z] (+ x (+ y z))) fn*)

I would expect it to return this:

    ((((z y +) x +) [x y z]) fn*)

**Comment by ztellman** [comment]
You're responsible for recursively calling walk-exprs yourself whenever an
expr matches. If you have any suggestions on how this can be made more
clear in the documentation, please let me know.

**Comment by lincoln-b** [comment]
Oh, I see.

My confusion came because calling this:

    (riddley.walk/walk-exprs println identity '(defn xyz [x y z] (+ x (+ y z))))

Returns this:
```

(def xyz (clojure.core/fn ([x y z] (+ x (+ y z)))))
xyz
(fn* ([x y z] (+ x (+ y z))))
(. clojure.lang.Numbers (add x (+ y z)))
clojure.lang.Numbers
x
(. clojure.lang.Numbers (add y z))
clojure.lang.Numbers
y
z
(def xyz (fn* ([x y z] (. clojure.lang.Numbers (add x (. clojure.lang.Numbers (add y z)))))))
```

I suppose the predicate runs recursively by default, but the second function doesn't?

**Comment by ztellman** [comment]
If the predicate matches, it's your job to transform the entire matched
expression, if necessary by calling walk-exprs on the sub-expressions. If
there's no match, the predicate will descend deeper into the syntax tree.

**Comment by lincoln-b** [comment]
Why does the second example (the one with inc) work without calling walk-exprs on the sub-expressions?

**Comment by ztellman** [comment]
Because it's not matching on the whole expression, it's matching on the individual terms (numbers).  Since there are no sub-expressions, you're not required to manually descend.
